#!/bin/bash

ans=(0)

while true; do
    # read input from the user
    expression=$(printf "%s\n" "${ans[@]}" | fuzzel --mesg "fuzzel calculator" --width 50 --dmenu -p "calc (ans=${ans[-1]}): ")
    # check if the input is empty
    if [[ -z "$expression" ]]; then
        # quit
        break
    fi
    # replace any ans by the variable $ans
    expression=$(echo "scale=3; $expression" | sed "s/ans/${ans[-1]}/g")
    result=$(echo "$expression" | bc -l 2>&1)
    if [[ "$result" =~ [Ee]rror ]] || [[ ! "$result" =~ ^-?[0-9]*\.?[0-9]+$ ]] || [[ $result =~ 0 ]]; then
        continue
    fi
    # evaluate the expression
    ans+=("$result")
done
